config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('diagnostics.urls', namespace='diagnostics')),
    path('user/', include('user.urls', namespace='user'))
]

diagnostics/urls.py
from django.urls import path

from diagnostics.apps import DiagnosticsConfig
from diagnostics.views import DirectionsListView, DoctorListView, DiagnosticListView, DoctorDeleteView, \
    DiagnosticDeleteView, DirectionsDeleteView, DirectionsDetailView, ReviewListView, ReviewCreateView, \
    ReviewUpdateView, ReviewDeleteView

app_name = DiagnosticsConfig.name


urlpatterns = [
    # Главная страница
    path('', DirectionsListView.as_view(), name='home_page'),
    path('delete_directions/<int:pk>/', DirectionsDeleteView.as_view(), name='delete_directions'),
    path('directions_detail/<int:pk>/', (DirectionsDetailView.as_view()), name='directions_detail'),

    # Доктора
    path('doctors/', DoctorListView.as_view(), name='doctors'),
    path('delete_doctor/<int:pk>/', DoctorDeleteView.as_view(), name='delete_doctor'),

    # Услуги
    path('diagnostic_list/', DiagnosticListView.as_view(), name='diagnostic_list'),
    path('delete_diagnostic/<int:pk>/', DiagnosticDeleteView.as_view(), name='delete_diagnostic'),

    # Отзыв
    path('review_list/', ReviewListView.as_view(), name='review_list'),
    path('review_create/', ReviewCreateView.as_view(), name='review_create'),
    path('review_update/<int:pk>/', ReviewUpdateView.as_view(), name='review_update'),
    path('review_delete/<int:pk>/', ReviewDeleteView.as_view(), name='review_delete'),
]

user/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from user.apps import UserConfig
from user.views import RegisterView, generate_new_password, \
    UserLogin, users, UserConfirmEmailView, UserConfirmedView, \
    UserConfirmationFailView, regenerate_password, UserConfirmationSentView, UserUpdateView, UserDetailView

app_name = UserConfig.name


urlpatterns = [
    path('users', users),
    path('login/', UserLogin.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('confirm_email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email_confirmed/', UserConfirmedView.as_view(), name='email_confirmed'),
    path('email_confirmation_failed/', UserConfirmationFailView.as_view(), name='email_confirmation_failed'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
    path('regenerations/', regenerate_password, name='regenerate_password'),
    path('email_confirmation_sent/', UserConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('profile/update/', UserUpdateView.as_view(), name='profile_update'),
    path('profile/', UserDetailView.as_view(), name='profile'),
]

diagnostics/models.py
from django.db import models

from user.models import User

NULLABLE = {'blank': True, 'null': True}


class Directions(models.Model):
    title = models.CharField(max_length=100, verbose_name='Название направления')
    description = models.CharField(max_length=500, verbose_name='Описание', **NULLABLE)
    icon = models.ImageField(upload_to='icons/', verbose_name='Иконка', **NULLABLE)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Направление'
        verbose_name_plural = 'Направления'


class Doctor(models.Model):
    fio = models.CharField(max_length=100, verbose_name='ФИО')
    directions = models.ForeignKey(Directions, on_delete=models.CASCADE, verbose_name='Направление')
    experience = models.IntegerField(verbose_name='Стаж')
    add_info = models.CharField(max_length=300, verbose_name='Дополнительная информация')
    timing = models.CharField(verbose_name='Часы приёма', **NULLABLE)

    def __str__(self):
        return f'{self.fio}'

    class Meta:
        verbose_name = 'Врач'
        verbose_name_plural = 'Врачи'


class Diagnostic(models.Model):
    title = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание', **NULLABLE)
    price = models.PositiveIntegerField(verbose_name='Стоимость')
    doctor = models.ManyToManyField('Doctor', related_name="Врач")

    def __str__(self):
        return f'{self.title}: {self.price}'

    class Meta:
        verbose_name = 'Услуга'
        verbose_name_plural = 'Услуги'


class Review(models.Model):
    text = models.CharField(max_length=500, verbose_name='Текст')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пациент', **NULLABLE)

    def __str__(self):
        return f'{self.user} - {self.text}'

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

diagnostics/forms.py
from django import forms

from diagnostics.models import Review


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ReviewForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Review
        fields = ('text',)

diagnostics/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import Http404
from django.urls import reverse_lazy
from django.views.generic import ListView, DeleteView, DetailView, CreateView, UpdateView

from diagnostics.forms import ReviewForm
from diagnostics.models import Directions, Doctor, Diagnostic, Review


# Направления
class DirectionsListView(ListView):
    model = Directions
    template_name = 'diagnostics/home_page.html'


class DirectionsDeleteView(DeleteView):
    model = Directions
    # success_url = reverse_lazy('diagnostics:blog_list')


class DirectionsDetailView(DetailView):
    model = Directions
    permission_required = 'diagnostics.directions_detail'


# Доктора
class DoctorListView(ListView):
    model = Doctor
    template_name = 'diagnostics/doctors.html'

    # def get_context(self):
    #     context_data = get_category_cache()
    #     return context_data

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset


class DoctorDeleteView(DeleteView):
    model = Doctor


# Услуги
class DiagnosticListView(ListView):
    model = Diagnostic
    template_name = 'diagnostics/diagnostic_list.html'


class DiagnosticDeleteView(DeleteView):
    model = Diagnostic


# Отзывы
class ReviewCreateView(LoginRequiredMixin, CreateView):
    model = Review
    form_class = ReviewForm
    success_url = reverse_lazy('diagnostics:review_list')

    def form_valid(self, form):
        if form.is_valid():
            product = form.save()
            product.user = self.request.user
            product.save()

        return super().form_valid(form)


class ReviewListView(ListView):
    model = Review
    template_name = 'diagnostics/review_list.html'


class ReviewDeleteView(DeleteView):
    model = Review
    success_url = reverse_lazy('diagnostics:review_list')


class ReviewUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Review
    form_class = ReviewForm
    success_url = reverse_lazy('diagnostics:review_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user and not self.request.user.is_staff:
            raise Http404("Вы не являетесь владельцем этого товара")
        return self.object

    def test_func(self):
        _user = self.request.user
        _instance: Review = self.get_object()

        if _user == _instance.user:
            return True

        return self.handle_no_permission()

diagnostics/templates/diagnostics/base.html
{% load static %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>{{ title }}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/pricing/">



    <!-- Bootstrap core CSS -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="pricing.css" rel="stylesheet">
  </head>
  <body>

<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="check" viewBox="0 0 16 16">
    <title>Check</title>
    <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
  </symbol>
</svg>

<div class="container py-3">

  {% include 'diagnostics/includes/inc_diagnostics_menu.html' %}

  <main>
    {% block content %}
    {% endblock %}
  </main>


  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <p class="col-md-4 mb-0 text-body-secondary">Номер регистратуры +7 950 000 11 22</p>

    <a class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none" href="{% url 'diagnostics:review_list'%}">
      Оставить отзыв
    </a>

    <ul class="nav col-md-4 justify-content-end">
      <li class="nav-item"><a href="{% url 'diagnostics:home_page'%}" class="nav-link px-2 text-body-secondary">Главная</a></li>
      <li class="nav-item"><a href="{% url 'diagnostics:doctors' %}" class="nav-link px-2 text-body-secondary">Наши врачи</a></li>
      <li class="nav-item"><a href="{% url 'diagnostics:diagnostic_list' %}" class="nav-link px-2 text-body-secondary">Наши услуги</a></li>
    </ul>
  </footer>
</div>



  </body>
</html>

diagnostics/templates/diagnostics/diagnostic_list.html
{% extends 'diagnostics/base.html' %}
{% load static %}
{% block content %}


 <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Наши услуги</h1>
        <p class="lead text-body-secondary">Запись производится по номеру +7 950 000 11 22</p>
      </div>
    </div>
  </section>


<div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for object in object_list %}
        <div class="col-sm-6 mb-3 mb-sm-0">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">{{ object.title }}</h5>
                <p class="card-text">{{ object.description }}</p>
                <p class="card-text">Стоимость: {{ object.price }} руб.</p>

              </div>
            </div>
        </div>
        {% endfor %}
      </div>
</div>


{% endblock %}

diagnostics/templates/diagnostics/directions_detail.html
{% extends 'diagnostics/base.html' %}

{% block content %}

<div class="card">
  <div class="card-header">
    {{ object.title }}
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p>{{ object.description }}</p>
    </blockquote>
  </div>
</div>

{% endblock %}

diagnostics/templates/diagnostics/doctors.html
{% extends 'diagnostics/base.html' %}
{% load static %}
{% block content %}


<section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Наши специалисты</h1>
        <p class="lead text-body-secondary">Запись на приём производится по номеру +7 950 000 11 22</p>
      </div>
    </div>
</section>

{% for object in object_list %}
<div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{% static 'icons/1673499692_gas-kvas-com-p-risunok-detskii-doktor-13.jpg' %}" width="179.33" height="250" alt="icon">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{ object.fio }}</h5>
        {% if object.experience > 4 %}
        <p class="card-text">{{ object.directions }}.
        Стаж {{ object.experience }} лет</p>
        <p class="card-text"> Часы приёма:</p>
        <p class="card-text">{{ object.timing }}</p>
        {% else %}
        <p class="card-text">{{ object.directions }}.
        Стаж {{ object.experience }} года</p>
        <p class="card-text"> Часы приёма:</p>
        <p class="card-text">{{ object.timing }}</p>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endfor %}

{% endblock %}

diagnostics/templates/diagnostics/home_page.html
{% extends 'diagnostics/base.html' %}
{% load static %}
{% block content %}
<img src="{% static 'icons/123.jpg' %}" class="img-fluid" width="1680" height="776">

  <div class="album py-5 bg-body-tertiary">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for object in object_list %}
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <p class="card-text">{{object.title}}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{% url 'diagnostics:directions_detail' object.pk %}" class="btn btn-outline-primary" type="button" >Подробнее</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}

{% endblock %}

diagnostics/templates/diagnostics/review_confirm_delete.html
{% extends 'diagnostics/base.html' %}

{% block content %}
<form class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Вы уверены, что хотите удалить "{{ object.text }}"?</p>
                            <button type="submit" class="btn btn-danger"> Удалить </button>
                            <a href="{% url 'diagnostics:review_list' %}" class="btn btn-warning"> Отмена </a>
                        </form>
                    </div>
                </div>
            </div>
        </form>
    <form>
{% endblock %}

diagnostics/templates/diagnostics/review_form.html
{% extends 'diagnostics/base.html' %}

{% block content %}
<div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Отзыв
                        </h3>
                    </div>
                    <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-outline-primary">
                              {% if object %}
                              Сохранить
                              {% else %}
                              Создать</button>
                              {% endif %}
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

diagnostics/templates/diagnostics/review_list.html
{% extends 'diagnostics/base.html' %}

{% block content %}


<section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Отзывы</h1>
      </div>
    </div>
</section>

{% if user.is_authenticated %}
  <div class="col-12 mb-3">
    <a class="btn btn-outline-primary" href="{% url 'diagnostics:review_create' %}">Оставить отзыв</a>
    {% else %}
    <p class="lead text-body-secondary">Авторизуйтесь чтобы оставить отзыв</p>
{% endif %}
  </div>

{% for object in object_list %}
<div class="container">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">{{ object.user }}</h5>
      <p class="card-text">{{ object.text }}</p>
      {% if object.user == user %}
      <div class="btn-group btn-group-sm" role="group" aria-label="Small button group">
        <a href="{% url 'diagnostics:review_update' object.pk %}" class="btn btn-outline-primary">Изменить</a>
        <a href="{% url 'diagnostics:review_delete' object.pk %}" class="btn btn-outline-primary">Удалить</a>
      </div>
      {% endif %}
    </div>
  </div>
</div>
{% endfor %}

{% endblock %}