config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('diagnostics.urls', namespace='diagnostics')),
    path('user/', include('user.urls', namespace='user'))
]

user/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from user.apps import UserConfig
from user.views import RegisterView, generate_new_password, \
    UserLogin, users, UserConfirmEmailView, UserConfirmedView, \
    UserConfirmationFailView, regenerate_password, UserConfirmationSentView, UserUpdateView, UserDetailView

app_name = UserConfig.name


urlpatterns = [
    path('users', users),
    path('login/', UserLogin.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('confirm_email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email_confirmed/', UserConfirmedView.as_view(), name='email_confirmed'),
    path('email_confirmation_failed/', UserConfirmationFailView.as_view(), name='email_confirmation_failed'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
    path('regenerations/', regenerate_password, name='regenerate_password'),
    path('email_confirmation_sent/', UserConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('profile/update/', UserUpdateView.as_view(), name='profile_update'),
    path('profile/', UserDetailView.as_view(), name='profile'),
]

user/models.py
import random

from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank':  True, 'null': True}


code = ''.join([str(random.randint(0, 9)) for _ in range(12)])


class User(AbstractUser):
    username = None
    first_name = models.CharField(max_length=20, verbose_name='Имя')
    last_name = models.CharField(max_length=20, verbose_name='Фамилия')
    birthday = models.DateField(verbose_name='Дата рождения')
    email = models.EmailField(unique=True, verbose_name='E-mail')
    telegram = models.CharField(unique=True, max_length=20, verbose_name='Telegram', **NULLABLE)
    phone = models.CharField(unique=True, max_length=20, verbose_name='Номер телефона')
    ver_code = models.CharField(max_length=15, default=code, verbose_name='Проверочный код')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return f'{self.first_name}'

    class Meta:
        verbose_name = 'Пациент'
        verbose_name_plural = 'Пациенты'

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from user.models import User


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'birthday', 'email', 'phone', 'password1', 'password2')


class UserProfileForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'birthday', 'email', 'password', 'phone')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

user/views.py
from django.conf import settings
from django.contrib.auth import logout, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import LogoutView, LoginView, PasswordResetDoneView
from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.urls import reverse_lazy, reverse
from django.utils.crypto import get_random_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import View
from django.views.generic import CreateView, UpdateView, TemplateView

from user.forms import UserRegisterForm, UserProfileForm
from user.models import User

from django.utils.translation import gettext_lazy as _


def users(request):
    user = User.objects.all()
    return render(request, 'user/user.html', {'user': user})


class UserLogin(LoginView):
    template_name = 'user/login.html'
    success_url = reverse_lazy('diagnostics:home_page')


class UserLogout(LogoutView):
    http_method_names = ["post", "options"]
    template_name = "diagnostics/home_page.html"
    extra_context = None

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        """Logout may be done via POST."""
        logout(request)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "site": 'home_page',
                "site_name": 'home_page',
                "title": _("Logged out"),
                "subtitle": None,
                **(self.extra_context or {}),
            }
        )
        return context


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('user:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        user.save()

        token = default_token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        activation_url = reverse_lazy('user:confirm_email', kwargs={'uidb64': uid, 'token': token})

        current_site = '127.0.0.1:8000'

        send_mail(
            subject='Регистрация на платформе',
            message=f"Завершите регистрацию, перейдя по ссылке: http://{current_site}{activation_url}",
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email]
        )
        return redirect('user:email_confirmation_sent')


class UserConfirmEmailView(View):

    def get(self, request, uidb64, token):
        try:
            uid = urlsafe_base64_decode(uidb64)
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            login(request, user)
            return redirect('user:email_confirmed')
        else:
            return redirect('user:email_confirmation_failed')


class UserConfirmedView(TemplateView):
    """ Выводит информацию об успешной регистрации пользователя """
    template_name = 'user/registration_confirmed.html'


class UserConfirmationFailView(View):
    """ Выводит информацию о невозможности зарегистрировать пользователя """
    template_name = 'user/email_confirmation_failed.html'


class UserConfirmationSentView(PasswordResetDoneView):
    """ Выводит информацию об отправке на почту подтверждения регистрации """
    template_name = "user/registration_sent_done.html"


def generate_new_password(request):
    """ Генерирует новый пароль пользователя """
    new_password = get_random_string(length=9)

    send_mail(
        subject='Новый пароль',
        message=f'Ваш новый пароль: {new_password}',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email]
    )

    request.user.set_password(new_password)
    request.user.save()

    return redirect(reverse('catalog:home'))


def regenerate_password(request):
    """ Генерирует новый пароль пользователя """
    if request.method == 'POST':
        email = request.POST.get('email')
        # Получаем пользователя по email
        user = User.objects.get(email=email)

        # Генерируем новый пароль
        new_password = get_random_string(length=9)

        # Изменяем пароль пользователя
        user.set_password(new_password)
        user.save()

        # Отправляем письмо с новым паролем
        send_mail(
            subject='Восстановление пароля',
            message=f'Ваш новый пароль: {new_password}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[email],
            fail_silently=False,
        )

        return redirect(reverse('catalog:home'))
    return render(request, 'user/regenerate_password.html')


class UserUpdateView(UpdateView):
    model = User
    success_url = reverse_lazy('user:profile')
    form_class = UserProfileForm

    def get_object(self, queryset=None):
        return self.request.user


class UserDetailView(LoginRequiredMixin, View):

    def get(self, request):
        user = request.user
        context = {
            'object': user,
        }
        return render(request, 'user/profile.html', context)

user/templates/user/email_confirmation_failed.html
{% extends 'diagnostics/base.html' %}

{% block content %}

<div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">Ошибка</h4>
    <p>Не удалось подтвердить вашу электронную почту. Попробуйте еще раз</p>
</div>

{% endblock %}

user/templates/user/login.html
{% extends 'diagnostics/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Вход
                        </h3>
                    </div>
                    <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-outline-primary">Войти</button>
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

user/templates/user/msg_email.html
{% extends 'diagnostics/base.html' %}

{% block content %}
  <div class="col-12">
      <form class='row' method="post" enctype="multipart/form-data">
          <div class="col-4"></div>
          <div class="col-4">
            <div class="card">
              <div class="card-header">
                <h4 class="card-title">Верификация почты</h4>
                <p class="lead text-body-secondary">Введите проверочный код</p>
              </div>
              <div class="card-body">
                  {% csrf_token %}

                  <input type="text" name="ver_code" class="form-control" id="ver_code" required>
              </div>
              <div class="card-footer">
                  <button type="submit" class="btn btn-outline-primary">Подтвердить</button>
              </div>
            </div>
          </div>
      </form>
  </div>
{% endblock %}

user/templates/user/profile.html
{% extends 'diagnostics/base.html' %}
{% load static %}

{% block content %}
<div class="col-md-12">
    <div class="card flex-md-row mb-4 box-shadow h-md-250">
        <div class="card-body d-flex flex-column align-items-start">
            <h1 class="display-5 fw-bolder">{{ user.first_name }} {{ user.last_name }}</h1>
            <div class="medium mb-1">Дата рождения: {{ user.birthday }}</div>
            <div class="medium mb-1">e-mail: {{ user.email }}</div>
            <div class="medium mb-1">Номер телефона: {{ user.phone }}</div>
            <a href="{% url 'user:profile_update' %}" class="btn btn-primary my-2">Редактировать профиль</a>
        </div>
    </div>
    <div class="card-body">
    </div>
</div>
{% endblock %}

user/templates/user/regenerate_password.html
{% extends 'diagnostics/base.html' %}


{% block content %}

<div class="container">
    <div class="row text-start">
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Сгенирировать пароль</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="exampleFormControlInput1" class="form-label">Email address</label>
                            <input type="email" name="email" class="form-control" id="exampleFormControlInput1"
                                   placeholder="name@example.com">
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Сгенирировать пароль</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

user/templates/user/register.html
{% extends 'diagnostics/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Регистрация
                        </h3>
                    </div>
                    <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="w-100 btn btn-lg btn-outline-primary">Зарегистрироваться</button>
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

user/templates/user/registration_confirmed.html
{% extends 'diagnostics/base.html' %}

{% block content %}

<div class="alert alert-success" role="alert">
    <h4 class="alert-heading">Успешно</h4>
    <p>Ваша электронная почта подтверждена</p>
</div>

{% endblock %}

user/templates/user/registration_sent_done.html
{% extends 'diagnostics/base.html' %}

{% block content %}

<div class="alert alert-warning" role="alert">
    <h4 class="alert-heading">Вам на почту, указанную при регистрации, отправлено письмо</h4>
    <br>
    <p>Для успешной регистрации перейдите по ссылке, указанной в письме</p>
</div>

{% endblock %}

user/templates/user/user_form.html
{% extends 'diagnostics/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Профиль
                        </h3>
                    </div>
                    <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-outline-primary">Сохранить</button>
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

user/templates/user/verify_email_error.html
{% extends 'diagnostics/base.html' %}

{% block content %}
  <div class="col-12">
      <form class='row' method="post" enctype="multipart/form-data">
          <div class="col-4"></div>
          <div class="col-4">
            <div class="card">
              <div class="card-header">
                <h4 class="card-title">
                  Неверный код
                </h4>
              </div>
              <div class="card-body">
              </div>
              <div class="card-footer">
                  <a href="{% url 'user:verify_email' %}" class="btn btn-outline-primary">Повторить попытку</a>
              </div>
            </div>
          </div>
      </form>
  </div>
{% endblock %}